### ISSUE TITLE
add additional info from imaging/targeting catalogs

### ISSUE THREAD

**Issue by moustakas** [desihub/prospect#21]
Spun off from #17.

Let's use this issue to tabulate the additional information from the imaging that would be useful to have for each target/object while assessing/visualizing the redshift fits.

* morphology

**Comment by armengau** [comment]
Also requested by Boris Gaensicke some time ago:
add the target coordinates (where it can be grabbed for cut & paste)

**Comment by armengau** [comment]
Done in PR #70
