### ISSUE TITLE
Is it possible to save out spectral data to JSON file?

### ISSUE THREAD

**Issue by Samreay** [desihub/prospect#22]
Hi team!

I understand the current version of Prospect uses bokeh to save out HTML files. I was wondering if it was also possible to gather the data and output to a JSON file in the same (or a similar) directory for easier digestion of data by other users? Something that takes a simple form like:

```
{
  name: "somename",
  wavelength: [lambdas...],
  flux: [three_arms_combined...]
  flux_err: [err...],
  etc
}
```

I notice the bokeh setup in plotframes.py, however thought it would be good to start a discussion here before volunteering code changes! 

Would the team be open to adding this functionality, (happy to help with the coding as well)?

**Comment by armengau** [comment]
Hi Sam,
First thanks for your input few weeks ago, that helped a lot !
About your request, actually I was wondering if such a functionality should be implemented within prospect, or in desispec since it's just a data reformatting ?

**Comment by Samreay** [comment]
Hey Eric! 

I'm not too sure where the best place would be, am very unfamiliar with the different code repos. I was thinking that the right place to put it is in whichever code currently has the algorithm to combine the arms into a single wavelength/flux array so that there isn't code duplication. Is that algorithm within prospect or external?

**Comment by armengau** [comment]
There is a coaddition fct in desispec, but in prospect I had to reimplement a light version in javascript, so that coaddition is done by the browser, and html pages contain only single-arm spectra. Better duplicate (simple) code than double the volume of html pages that are downloaded.

**Comment by Samreay** [comment]
Would you be able to point me to both of the code snippets that do this? The desispec fn and the javascript? 

In terms of potentially adding something to desispec then, how does prospect hook into the pipeline to generate HTML when there's a new spectrum ready for processing? I can ask to do a similar thing to generate digestible JSON.

Cheers :)

**Comment by armengau** [comment]
The desispec fct is desispec.coaddition.coadd_cameras(). The javascript is in js/update_plot : function coadd_brz_cams(wave_in, flux_in, noise_in) at line 135 as of today.

As of now, prospect does not hook into the pipeline directly (not in the flow of daily jobs).
Creating pages from mock data, ie independently of having "new" spectra ready for processing is handled by scripts/specview_per_pixel.py
I'm working now on processing nightly commissioning data, still independently of the pipeline, code still under dev in scripts/specview_cmx_frames.py

**Comment by Samreay** [comment]
Okay, so just trying to figure out the right pieces to go where. If I can get a desispec function that creates a JSON format of that data, would the best step to then have prospect invoke it? Im trying to think of the number of hooks and keeping things synchronised, as any JSON file I imagine a user might want to inspect in Prospect. If prospect was the one invoking the desispec.to_json() (or similar) function, it would mean that there would always be a HTML counterpart to a JSON file. 

Would that work?

**Comment by armengau** [comment]
Ok, so there are 2 things:
- basic function creating a "simple" camera-coadded json file : I would put that in desispec.io, to discuss actually with pipeline people (eg S Bailey, J Guy)
- automatic production of json files : could indeed be done at the same time than bokeh/prospect html files. We'd have to be careful about disk usage but probably at least for SV it should be ok. Probably easy to be included in prospect scripts, indeed.

**Comment by Samreay** [comment]
Alright, let me hit up Stephen and Julien at the meeting and I'll run it by them. Cheers mate

**Comment by weaverba137** [comment]
@armengau, @Samreay, is this ever likely to be implemented?

**Comment by armengau** [comment]
@weaverba137 From my point of view I'm not sure it would ever really be needed. There are other (better) way to retrieve spectral data from eg a given targetid.

**Comment by weaverba137** [comment]
OK, I propose we close this issue then.
