### ISSUE TITLE
Inverse-variance weighted smoothing

### ISSUE THREAD

**Issue by janewman-pitt-edu** [desihub/prospect#23]
It'd be useful to have inverse-variance-weighted smoothing as an option (or default).

Simple algorithm:
ivarsmooth = smooth(data*ivar, n) / smooth(ivar,n)

where smooth(x,n) does a boxcar smooth in an n-pixel-wide window.  Smoothing this way suppresses fluctuations from skylines.

The DEEP2 IDL code for this is below. 
;+
; NAME:
;   ivarsmooth
;
; PURPOSE:
;   to generate inverse variance smoothed 1d spectrum
;
; CALLING SEQUENCE:
;   spec = ivarsmooth(flux,ivar,window,[outivar])
; 
; INPUTS:
;   flux -- spectrum to be smoothed
;   ivar -- inverse variance of this spectrum
;   window -- smoothing length in pixels (turned into odd number if
;             even or float)
; OPTIONAL INPUTS:
;	
; KEYWORDS:
;
; OUTPUTS:
;    spec -- resulting smoothed 1d array
;
; OPTIONAL OUTPUTS:
;   outivar -- resulting inverse variance
;
; RESTRICTIONS:
;    
; EXAMPLES:
;
; COMMENTS:
;
; REVISION HISTORY:
;  JAN 04jul2002, comments by MD
;----------------------------------------------------------------------

function ivarsmooth, flux, ivar, window, outivar

  s = size(flux)
  ndim = s[0]
  nflux = n_elements(flux)
  simpleflux = ndim eq 1 OR ndim eq 2 and (s[2] > s[1]) eq nflux

  if NOT simpleflux then begin
     message, 'Flux must be a 1-D array!', /continue
     return, flux
  endif

  flux = reform(flux)
  ivar = reform(ivar)

  halfwindow = floor( (round(window)-1)/2)

  shiftarr = fltarr(nflux, 2*halfwindow+1)
  shiftivar = shiftarr
  shiftindex = shiftarr
  indexarr = findgen(nflux)
  indnorm = (fltarr(2*halfwindow+1)+1) ## indexarr

  for i=-halfwindow, halfwindow do begin & $
     shiftarr(*, i+halfwindow) = shift(flux, i) & $
     shiftivar(*, i+halfwindow) = shift(ivar, i) & $
     shiftindex(*, i+halfwindow) = shift(indexarr, i) & $
  endfor

  wh = where( abs(shiftindex-indnorm) gt (halfwindow+1))
  shiftivar[wh] = 0.

  outivar = total(shiftivar, 2)
  nzero =  where(outivar gt 0,zeroct)
  smoothflux = total(shiftarr*shiftivar, 2)
  if zeroct gt 0 then smoothflux[nzero] = smoothflux[nzero]/outivar[nzero] $
     else smoothflux = smooth(flux,2*halfwindow+1);kill off NAN's

return, smoothflux
end

**Comment by armengau** [comment]
Update : from Kyle observation : "seeing some funny filtering around missing pixels, for example in the attached sequence that scales from no smoothing to 5-pixel smoothing, as indicated by figure names"
=> ivar-weighted smoothing must be implemented by default.

**Comment by janewman-pitt-edu** [comment]
Do you mean it is already implemented and causing a problem, or should be implemented?

**Comment by janewman-pitt-edu** [comment]
It would be straightforward to try to make the gaussian filter incorporate inverse variance  just by dropping in something like:

ivarsmooth = gaussian_filter(flux*ivar,sigma = n)/gaussian_sigma(ivar, sigma=n)

though you'd have to do something to trap NaNs when ivar = 0 over the whole window.  Maybe something like:

is_not_finite = !(np.isfinite(ivarsmooth))
if ( np.sum( is_not_finite) > 0):
      ivarsmooth[is_not_finite] = median_filter(ivarsmooth, size=(5*n+1))
    is_not_finite2 = !(np.isfinite(ivarsmooth))
     if ( np.sum( is_not_finite2) > 0):
      ivarsmooth[is_not_finite] = np.median(ivarsmooth)

**Comment by janewman-pitt-edu** [comment]
ugh, I can't figure out how to get that to format right.  the key thing is the second `if` should be indented so it only happens if the first if is true.

**Comment by sbailey** [comment]
@janewman-pitt-edu triple backticks are the trick for multi-line markdown code formatting.  I updated your code comment with what I think you intended; please check.

**Comment by janewman-pitt-edu** [comment]
that looks as intended, thanks!

**Comment by armengau** [comment]
ivar-weighted smoothing was implemented in the disp-model branch, now merged to master.
I also adapted the formulas to the noise.
