### ISSUE TITLE
The last row in the spreadsheet display does not get updated in display

### ISSUE THREAD

**Issue by biprateep** [desihub/prospect#28]
The last row in the spreadsheet display does not get updated in display but the corresponding input values are saved in the VI download file

**Comment by armengau** [comment]
I could not reproduce this issue, at least with current prospect version.
@biprateep Tell me if you still have the problem using eg. pages in https://portal.nersc.gov/project/desi/collab/prospect/sv0/

Maybe this is a confusion due to the fact that spectrum numbers range from 0 to N-1 (and not N)

**Comment by armengau** [comment]
I checked the issue is not there since 0.1.0
