### ISSUE TITLE
Value of redshift rough tuning is incorrect in special cases

### ISSUE THREAD

**Issue by bjweiner** [desihub/prospect#36]
I found some odd behavior in the redshift rough tuning slider.I am looking at the first set of SV0 BGS spectra (resident at NERSC, non-public, link ending in sv0/tiles_SV0_BGS/66003/20200315/ ). On object 22, in the first screenshot I have just clicked "reset redshift", the pipeline z=0.2600, but the rough tuning slider says z=0.28.  The spectrum plot is showing z=0.2600, which is correct.

When I then click right-arrow to go to the next object (2nd screenshot), which has pipeline z=0.5848, now the rough tuning slider shows z=0.56 and the model spectrum is plotted for z=0.5648, which is wrong. Clicking "reset redshift" sets it to the correct pipeline value.

I would not be surprised if this is some weird truncation behavior caused by an object with z=0.nn00. It's weird that an offset appears to persist between the objects.

<img width="1090" alt="specviewer_after_reset_z" src="https://user-images.githubusercontent.com/5199143/78085445-d88e7400-736f-11ea-9b80-4e2904b0d401.png">
<img width="1083" alt="specviewer_next_object" src="https://user-images.githubusercontent.com/5199143/78085458-e0e6af00-736f-11ea-8d4c-2ee612f88e5c.png">

**Comment by armengau** [comment]
Thanks, this example helped to debug this known issue.
It is in principle fixed in the new version of prospect ("redshift-handling" branch).
On April 10th prospect html pages for minisv2 and sv0 were redone with this new version, so this issue should be solved.
