### ISSUE TITLE
Prospect_demo.ipynb is not actually a notebook

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#37]
Prospect_demo.ipynb is actually an HTML file, not a notebook.  If you want to check in HTML, please check in both HTML *and* the actual notebook.

**Comment by weaverba137** [comment]
In fact, it's even worse than that, because the HTML is a copy of a GitHub page that shows the HTML failing to load.  As far as I can tell this is a total loss.  This may require deep searching through the git commit history to find a valid version.

**Comment by armengau** [comment]
Prospect_demo.ipynb is now a notebook again, compatible in principle with prospect branch pip-installable-package.
I should still update the demo code in this old notebook.

**Comment by armengau** [comment]
Notebook updated
