### ISSUE TITLE
Smoothing kernel bug?

### ISSUE THREAD

**Issue by armengau** [desihub/prospect#40]
Since the beginning the smoothing kernel is:

```
        var kernel = [];
        for(var i=-2*nsmooth; i<=2*nsmooth; i++) {
            kernel.push(Math.exp(-(i**2)/(2*nsmooth)))
        }
```

@weaverba137 I'd say that it should be` exp( -i**2/(2*nsmooth**2) )` do you agree ?
I found this while updating the function to handle issue https://github.com/desihub/prospect/issues/23

**Comment by weaverba137** [comment]
I'm not an expert on pixelated Gaussian kernels, but certainly a standard Gaussian should have `nsmooth**2`. Also, there is no normalization factor, but maybe that's not important for this?

**Comment by armengau** [comment]
Ok, thanks, so I'll go for nsmooth**2
The normalization is done later on (during smoothing)
