### ISSUE TITLE
Add a cross-hair or zoom in imaging figure

### ISSUE THREAD

**Issue by armengau** [desihub/prospect#41]
There were requests (B. Gaensicke, and others) to be able to better identify the central object (target) in the imaging thumbnail.
In some cases with several close-by objects, the identification of the targeted object in the image was not easy. Going to the link to the legacy survey viewer page does not help apparently.
- @weaverba137 : Is it possible to add a cross-hair centered on target to the image, either within prospect ? or in the legacy viewer itself? For prospect, I didn't find a way to overlay two figures in bokeh (but didn't look extensively either)
- Another suggestion was to zoom more in this picture, but I'm not sure it's best

**Comment by weaverba137** [comment]
@dstndstn , Does the Viewer image cutout API support crosshairs?

I agree, a higher zoom level might not add much more information, and may actually be detrimental for more nearby, extended objects: BGS, etc.  Still, that's something that's easy to test.

**Comment by moustakas** [comment]
This was just discussed here:
https://github.com/legacysurvey/decals-web/issues/72#issuecomment-623488399

**Comment by armengau** [comment]
Thanks !
- So I made a dummy mistake in my tests, I can actually easily add the cross-hair directly in prospect (bokeh), no need to get it from the legacy viewer.
- And indeed we can also link to the viewer with "&mark=RA,DEC".

**Comment by armengau** [comment]
Prospect edited (my dev branch "disp-models"): cross-hair done with native bokeh, and the legacysurvey viewer link is with a mark.
Thanks again.

**Comment by dstndstn** [comment]
I see you've already resolved this, but to answer @weaverba137 's question, no, the viewer cutout links don't support any annotations -- in the viewer itself, those are all done on the client side (by the web browser / Leaflet javascript library).  It's certainly possible to add (John Moustakas's student Iain did something like this for visual inspection of large galaxy fits), but not currently or planned part of the API.
