### ISSUE TITLE
Rest-frame display

### ISSUE THREAD

**Issue by armengau** [desihub/prospect#44]
Since the major redshift-handling changes, the x-axis range when in "rest-frame" mode does not behave correctly.
=> Needs to be corrected.

**Comment by armengau** [comment]
Very probably related to this issue - From Ting-Wen Lan & Michael Walther:

1) I have found that occasionally when the Prospect was opened, the redshift value is off by 0.01 from the best fit redshift value (please see the attached image). Some inspectors use to copy z to VI and will report a redshift which is inconsistent with the redrock. 
<img width="513" alt="Screen Shot 2021-01-22 at 4 28 43 PM" src="https://user-images.githubusercontent.com/48206451/105472904-c255f980-5c9c-11eb-8660-fcec4de2b1e2.png">

2) I noticed something weird in prospect, for some redshifts the rough
redshift slider does not seem to work properly, while the "redshift
value" gets updated, the value printed behind "rough tuning" is not. And
whenever the "fine tuning" is used after, the old rough tuning value is
used, i.e. the fine tuning slider is useless for some redshifts.
Example:
for me TARGET 35185947943375381 (spectrum 35 from
https://data.desi.lbl.gov/desi/spectro/prospect/target-reinspection-andes/QSO_68002/specviewer_QSO_reinspection_68002_3.html)
does not allow me to use rough redshift 0.03, 0.06, 0.08, 0.11, 0.15,
0.18,... (when sliding to higher values) and ..., 0.17, 0.14, 0.11,
0.08, 0.05, 0.02 (when sliding down).

**Comment by weaverba137** [comment]
Interesting.  That may be due to peculiarities of rounding in the JavaScript Math library.  Let me know if you need help investigating.

**Comment by weaverba137** [comment]
@armengau, is this bug fixed by #73?

**Comment by armengau** [comment]
Fixed by #73
