### ISSUE TITLE
Strange plot limits calculated by update_plot.js

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#46]
When the first object in a set of objects is plotted in prospect, the y-axis range is extremely simple: `min(flux), max(flux)` (after removing `NaN`, if any).

However, when subsequent objects are advanced to, a completely different, and rather complex algorithm is used.  Here's an outline of the procedure in pseudo-code:
```
ymin = ymax = 0
for each spectrograph:
    sort the flux
    # find the pixel index which corresponds to 1% of the pixels
    imin = floor(0.01*len(flux))
    # find the pixel index which corresponds to 99% of the pixels
    imax = floor(0.99*len(flux))
    # sort the flux
    sorted_flux = sort(flux)
    # use the value of the sorted flux at the pixels above as the new min, max
    ymin = min(ymin, sorted_flux[imin])
    ymax = max(ymax, sorted_flux[imax])
# now add additional padding
y_range.start = ymin < 0 ? ymin * 1.4 : ymin * 0.6
y_range.end = ymax * 1.4
```
What is it that motivates this complex algorithm?  In particular, it does not appear suitable for spectra with high signal to noise, or otherwise with a large dynamic range.

Why not just compute the actual min and max of the flux and be done with it?

**Comment by weaverba137** [comment]
Also, in JavaScript, `Array.sort()` without any arguments sorts values *as strings*.  See https://www.w3schools.com/jsref/jsref_sort.asp, which includes this exact quote:

> Because of this, the sort() method will produce an incorrect result when sorting numbers.

I am still very puzzled by the complexity of this algorithm, but fixing the sort method to actually sort numerically should help reduce some of the peculiarity here.

**Comment by armengau** [comment]
If I remember, this algorithm was in place when I started developing it.
The rational behind is probably that you don't want the y-range to be spoiled by a few pixels in the spectra with anomalously low/high values (due eg to data reduction problems, or high noise).

- from my experience VI-ing commissioning data, it works reasonably well, both with low and high-SNR spectra
- agree with the issue with javascript sort()

**Comment by sbailey** [comment]
The motivation for the yrange selection was what @armengau said: trying to find a yrange that would be robust against outliers on noisy spectra (thus the 1st and 99th percentiles) while still encompassing most of the range for high S/N spectra (thus the additional padding).

I don't recall exactly why the first object is treated differently, though it may have been a workaround for a bug in an earlier pre-1.0 release of bokeh (I remember futzing with trying to get it to do ranges correctly on the first draw).  It would be great to update that to be consistent for all objects with a common function.

Thanks for catching the `.sort()` bug (I continue to be amazed at how something as randomly bad as javascript became so prevalent...).

**Comment by weaverba137** [comment]
OK, I'll leave the algorithm as is for now, but document that it is rather complicated, and I will move the padding part so that it is adjacent to the other code that calculates the initial y limits.

**Comment by weaverba137** [comment]
The code that performs the algorithm above was moved physically closer together and documented in #43.
