### ISSUE TITLE
Display FIRST_EXPID,LAST_EXPID,FIRST_FIBER,LAST_FIBER

### ISSUE THREAD

**Issue by julienguy** [desihub/prospect#51]
It would be great if one could add to the prospect view the information about the exposure ids and fiber ids for the spectrum being displayed. Because the spectra are often coadds, there is not a single exposure id or even fiber, but there are the keywords  FIRST_EXPID,LAST_EXPID,FIRST_FIBER,LAST_FIBER in the fibermap. 

It would make it easier to find the original data when some bad features in the spectra are reported.

**Comment by armengau** [comment]
Done in PR #70
