### ISSUE TITLE
Search for specific targetID spectra

### ISSUE THREAD

**Issue by apalmese** [desihub/prospect#53]
It would be great if it was possible to see the spectrum/spectra for a specific targetID. This would be useful for example when our classifier reports a transient in a specific target.

**Comment by armengau** [comment]
This is possible, to view a (set of) targetid(s) use a jupyter notebook at Nersc as given by the example:
https://github.com/desihub/prospect/blob/master/doc/nb/Prospect_targetid.ipynb

Right now, for andes, you need to know in which (set of) tile(s) your spectra are.

@apalmese Tell me if that's ok, before I close this issue.
