### ISSUE TITLE
32-bit TARGETID in vi_file_fields

### ISSUE THREAD

**Issue by weaverba137** [desihub/prospect#57]
I'm pretty sure that TARGETID is a 64-bit integer, but it's described as 32-bit (`i4`) in `prospect.utilities.vi_file_fields`.  Is this a typo?

**Comment by weaverba137** [comment]
There are also issues with the types of `Spec_version`, `Redrock_version`, etc.  Those should be strings, but they are marked as integers in `vi_file_fields`.

**Comment by armengau** [comment]
Thanks for spotting that:

- I checked Targetid is int64 in the rest of the prospect python code. Actually, to pass targetids to js I had to use the following:
cds_targetinfo.add([str(x) for x in spectra.fibermap['TARGETID']], name='targetid') # !! No int64 in js !!
(this is in make_cds_targetinfo() in plotframes.py)

- The third column in prospect.utilities.vi_file_fields (data types) is actually never used, except for some functions in utilities.py (read_vi, initialize_master_vi). Those are obsolete, as handling csv VI files produced by VIers / finding conflicts / making VI truth tables is done using other VI code, independent from prospect.

So:

- I will anyway correct dtypes in prospect.utilities.vi_file_fields

- @weaverba137 For functions such as those utilities read_vi() , convert_vi_tofits()... that we know will remain useless and are obsolete, do you agree to completely remove them from the code ?

**Comment by weaverba137** [comment]
Here I was writing a unit test of `read_vi()`.  I'll abandon that test and leave the removal to another PR.

The nice thing is that removing useless code automatically increases unit test coverage.

**Comment by armengau** [comment]
`utilities.vi_file_fields` was cleaning in PR #70
