### ISSUE TITLE
Reset when going to a new spectrum

### ISSUE THREAD

**Issue by tamarastro** [desihub/prospect#61]
Currently if you set the VI spectype on one spectrum, it remains flagged on the next spectrum.  It doesn't actually mark the new spectrum unless you use the spectype dropdown menu again, but it looks like it is flagged and you have to move it away from e.g. QSO and then back again, when you want to mark QSO. 

Also, I'd like the zoom to reset to the full spectrum when I move to a new spectrum.  This may be a matter of taste, so is an optional change - feel free to ignore.

**Comment by armengau** [comment]
- Item (1) solved by https://github.com/desihub/prospect/pull/65
- I leave this issue open for item (2)

**Comment by weaverba137** [comment]
@armengau, is this fixed in #73?  Or some other PR?  The changes.rst file seems to suggest that it is.

**Comment by armengau** [comment]
Fixed in #73
