### ISSUE TITLE
Legend obscures spectral lines

### ISSUE THREAD

**Issue by tamarastro** [desihub/prospect#63]
While merging I noticed a semi-common failure mode, in which the VI missed a strong H-alpha or OII line at the red end of the spectrum, because the line was obscured by the legend.  To avoid having to move every spectrum in order to check whether something is under the legend, can we please extend the default wavelength axis so it goes far enough beyond the spectrum that the legend can fit without obscuring any of the spectrum?

**Comment by weaverba137** [comment]
@armengau, is this fixed in #73?  Or some other PR?  The changes.rst file seems to suggest that it is.

**Comment by armengau** [comment]
Fixed by #73
