### ISSUE TITLE
support redrock archetypes

### ISSUE THREAD

**Issue by sbailey** [desihub/prospect#7]
**To do:** Update Prospect to support redrock archetype fits in addition to redrock PCA fits.

### PCA-based redrock fits ###

Files at NERSC in /global/project/projectdirs/desi/datachallenge/svdc-summer2019/svdc2019c/spectro/redux/v1/spectra-64/101/10151/ are example outputs from PCA-based fits.  In that case the zbest table columns `SPECTYPE` and `SUBTYPE` indicate which PCA template set in /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/redrock-templates/master/ was the best match, and the `COEFF` column contains the coefficients to use with those templates to construct the best fit.  Prospect supports this, though there is the fragility that if prospect is run with a different version of $RR_TEMPLATE_DIR than was used when actually running redrock (rrdesi), it will use the wrong templates.

### Archetype-based redrock fits ###

Files at NERSC in /global/project/projectdirs/desi/datachallenge/svdc-summer2019/svdc2019c/spectro/redux/v1/tiles/70000/ are example outputs when redrock was run with --archetypes.  In that case it does an initial PCA-based chi2 vs. z scan, but then double checks minima using a suite of archetype spectra and choses the minimum with the best archetype fit instead of the minimum with the best PCA fit.  In the current redrock output, the PCA coefficients are lost.

For archetype redrock fits, zbest `SPECTYPE` indicates which file in /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/redrock-archetypes/master/ contained the best fit archetype, and the `SUBTYPE` column encodes which archtype was used.

e.g. `SPECTYPE == 'STAR'` and `SUBTYPE == 'M_17'` means the 17th row (counting from 0) in rrarchetype-star.fits.

Archetype fits also include additive Legendre polynomial coefficients.  It is probably best / easiest to directly use the [`redrock.archtype.Archetype.eval()`](https://github.com/desihub/redrock/blob/04a79fd3a4d9504f801fa8d1637b628aa7fb165a/py/redrock/archetypes.py#L63) code rather than port the details of the calculation, even those eval is lacking a docstring (e.g. I'd have to dig more to remember what the difference is between `wave` and `dwave` even though Hélion has told me...)

zbest files HDU 0 have header keywords like
```
TEMNAM00= 'GALAXY  '                                                            
TEMVER00= '2.6     '                                                            
TEMNAM01= 'QSO     '                                                            
TEMVER01= 'unknown '                                                            
...
```
giving some hint about which version of the templates was used, and if archtype fits were used there are additional keywords like
```
ARCNAM00= 'GALAXY  '                                                            
ARCVER00= 'v2.6    '                                                            
ARCNAM01= 'QSO     '                                                            
ARCVER01= '0.1...2018.06.21'                                                    
ARCNAM02= 'STAR    '                                                            
ARCVER02= '0.1...2018.06.21'                                                    
```
giving the version of the archtypes, which can be checked against the header keywords in /global/common/software/desi/cori/desiconda/20190804-1.3.0-spec/code/redrock-archetypes/master/

Ugh, this is a bit of a traceability / maintainability mess, but that's a brain dump of the current situation.

**Comment by michaelJwilson** [comment]
Archetypes were merged, so this can be closed out.
