### ISSUE TITLE
Gaussian smoothing slider not working: Uncaught ReferenceError: metadata is not defined

### ISSUE THREAD

**Issue by dstndstn** [desihub/prospect#71]
Hi,

I'm working on dynamically generating the prospect plots for the interactive sky viewer.

Stephen gave me some code to do this:
```
from desispec.io import read_tile_spectra
fibers = [259]
spectra, zbest = read_tile_spectra(80608, 'deep', specprod='blanc', coadd=True, fibers=fibers, zbest=True)
# Bonus
prospectpath = '/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/prospect/master/py'
if prospectpath not in sys.path:
    sys.path.append(prospectpath)
import prospect.plotframes
prospect.plotframes.plotspectra(spectra, zcatalog=zbest, html_dir='pro')
```

If I then open that pro/specviewer_specviewer.html file, and slide the Gaussian smoothing slider, I get in the Javascript console an error:

```
Uncaught ReferenceError: metadata is not defined
    anonymous https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js line 437 > Function:324
    execute https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:437
    n https://cdn.bokeh.org/bokeh/release/bokeh-2.3.1.min.js:218
...
```

This is coming from:
```
//
// Update redshift.
//
if (metadata.data['Z'] !== undefined && cb_obj == ifiberslider && model_select === null) {
    // if model_select is defined : this will be done in select_model.
    z_input.value = metadata.data['Z'][ifiber].toFixed(4);
}
```

so it looks like `metadata` is not getting set.

Any hints you could supply would be appreciated.  Thanks!

**Comment by dstndstn** [comment]
eg, (using a modified version of the code above to read the Denali formats),
 https://www.legacysurvey.org/viewer-desi/desi-spec-detail/denali/tile80688/fiber1190

**Comment by armengau** [comment]
Since recent major code restructure `prospect.plotframes` is deprecated, we should actually remove it completely.
Use the following:
```
import prospect.viewer
prospect.viewer.plotspectra(spectra, zcatalog=zbest, html_dir='pro')
```

**Comment by sbailey** [comment]
@dstndstn Please try again with `prospect.viewer.plotspectra` and let us know if that works.  I verified that the master installation at NERSC is up-to-date.  We also have the latest tag 1.1.1 installed (though I forgot to include it in the 21.3 software release, which still uses prospect/1.1.0).  If 1.1.1 works for the viewer, please use that so that we don't arbitrarily break you with some future master update (e.g. by renaming to main...)

**Comment by dstndstn** [comment]
Thank you very much, this works great!!
