### ISSUE TITLE
Error when missing 'r' camera?

### ISSUE THREAD

**Issue by dstndstn** [desihub/prospect#74]
An issue reported to me by Anand Raichoor:

> just reporting one corner-case, in case it is fixable: the following
targetid doesn t work, likely because the r-camera is not available in
the spectrum.

> targetid=39627747886112324
z=1.622
https://www.legacysurvey.org/viewer-desi/?ra=324.19768514&dec=-1.85466602&layer=ls-dr9&zoom=15&desi-spec-daily

> https://www.legacysurvey.org/viewer-desi/desi-spectrum/daily/targetid39627747886112324
=> error

> this object is row=494 of
/global/cfs/cdirs/desi/spectro/redux/daily/tiles/cumulative/1823/20210616/zbest-9-1823-thru20210616.fits
this tileid=1823 thrunight=20210616 reduction doesn t have r-camera.
though that object has ZWARN=FIBERSTATUS=0.

The error seems to be:  `create_model: Set of bands for spectra not supported`

I'm calling prospect like this: https://github.com/legacysurvey/imagine/blob/desi/map/cats.py#L183

Please let me know if this is an error in my calling sequence!

The end of the stack trace looks like:
```
 ./map/cats.py, line 183, in cat_desi_release_spectra_detail

        zbx = zbx[kk]
        zbests = zbx
        #- Confirm that we got all that expanding and sorting correct
        assert np.all(spectra.fibermap['TARGETID'] == zbests['TARGETID'])
        os.environ['RR_TEMPLATE_DIR'] = os.path.join(settings.DATA_DIR, 'redrock-templates')
        with tempfile.TemporaryDirectory() as d:
            prospect.viewer.plotspectra(spectra, zcatalog=zbests, html_dir=d)
            f = open(os.path.join(d, 'specviewer_specviewer.html'))
            return HttpResponse(f)
        return HttpResponse('tile %i fiber %i' % (tile, fiber))

./prospect/viewer/__init__.py, line 334, in plotspectra

                    raise ValueError("model fluxes do not match spectra (different nb of entries)")
            if model_from_zcat :
                # DESI spectra will obtain the model from templates.
                model = create_model(spectra, zcatalog,
                                     archetype_fit=archetype_fit,
                                     archetypes_dir=archetypes_dir,
                                     template_dir=template_dir)
        #-----
        #- Gather information into ColumnDataSource objects for Bokeh
        viewer_cds = ViewerCDS()
        viewer_cds.load_spectra(spectra, with_noise)
        if with_coaddcam :

./prospect/viewer/__init__.py, line 152, in create_model

            ] )
            mflux = np.concatenate( [
                model_flux['b'][:, keep['b']],
                model_flux['r'][:, keep['r']],
                model_flux['z'][:, keep['z']],
            ], axis=1 )
        else :
            raise RuntimeError("create_model: Set of bands for spectra not supported")

        return model_wave, mflux

```

**Comment by armengau** [comment]
@araichoor @dstndstn
You're calling prospect in the right way, and the error you get is a (design) feature.
Indeed
```
>>> sp=desispec.io.read_spectra('coadd-9-1823-thru20210616.fits')
>>> sp.bands
['b', 'z']
```
The DESI spectra fed to prospect are expected to be either a list of 3 frames, or a Spectra obj with 'brz' or 'b','r','z' bands.
Handling 2-arm data is certainly doable, but requires some coding especially in the javascript part (which is less flexible than python).

Do we actually expect to have 2-arm data ?? Indeed I see that in `daily/exposures`, there are no frames for r9 spectro for nights 20210611 to 20210616.

**Comment by araichoor** [comment]
yes, it does happen to have one missing arm, as you saw for those June data. I tripped into this.
though, those spectra should be discarded downstream by MTL and LSS (I m checking that with Adam and Ashley), so definitely a very low priority thing, if that requires some coding.
thanks for investigating!

**Comment by weaverba137** [comment]
Is this still an issue? Based on some unrelated work, I've been able to plot DESI data with a single "band" (actually a coadd across all three bands), and it worked fine.  So if spectra with a missing spectrograph can in fact be plotted, this should be closed.

**Comment by weaverba137** [comment]
@dstndstn, @araichoor, I'm trying to determine if this is still an active issue. Could you please check?

**Comment by araichoor** [comment]
sorry I m useless here, I just reported the issue in the legacysurvey link.

I can just mention that the link still reports an issue: https://www.legacysurvey.org/viewer-desi/desi-spectrum/daily/targetid39627747886112324.

I ve no idea if that s because there has been no change in the code to address that (though you say it now should work), or if it s because the legacsurvey link need some recomputation.

**Comment by armengau** [comment]
@weaverba137 Thanks for raising this again. Indeed also from my own experience, I agree this situation where one band is absent should be taken into account properly (it's not just some pathologic case from SV time).
When VI pages are created with the script `prospect_pages`, this issue is not so dramatic (we view the spectra, only get an unpleasant warning from the js code).
The issue is still dramatic with the legacyviewer interface.

I will investigate now.

**Comment by armengau** [comment]
Will be solved by https://github.com/desihub/prospect/pull/95
