### ISSUE TITLE
The gaussian smoothing gets undone when OLL zoom is applied

### ISSUE THREAD

**Issue by biprateep** [desihub/prospect#83]
Hi,
Not sure if this is intentional or not, but I am noticing that the gaussian smoothening gets undone if I use the OII zoom button. It will be great if the smoothing settings are preserved.

**Comment by armengau** [comment]
Hi Biprateep,
I forgot to answer after New Year's festivities..

This is an intentional feature:
- OII zoom => unset all gaussian smoothing (and zoom on the OII given the z value)
- "Undo OII zoom" => un-zooms, but also the previous gaussian smoothing is restored.

**Comment by biprateep** [comment]
I see, thanks for the response Eric!
